config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :friendships, only: [:index, :create, :destroy] 
  get '/friendships' => 'friendships#destroy', as: 'destroy_friendship_path'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :friend, class_name: "User", foreign_key: "friend_id", required: false

  def accept
  user.friends << friend
  destroy
  end

  def destroy
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :username, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
  end
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = Friendship.all
  end  
  
  def create
    @friendship = current_user.friendships.build(friend_params)
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end
  
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.delete
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end

  private

  def friend_params
    params.require(:friendship).permit(:user_id, :friend_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # protected

  # def after_inactive_sign_up_path_for(resource)
  #   '/users/sign_in'
  # end

  def new
    super
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id 
      flash[:notice] = "thank you for signing up! you are logged in"
      redirect_to root_path
    else
      render :new
    end    
  end

  def update
    super
  end

  private 
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show 
    @user = User.find(params[:id])
  end

  def new
    @user = user.new
  end 
  
  def create 
    @user = User.new(params[:user])
    if @user.save 
      session[:user_id] = @user.id 
      flash[:notice] = "thank you for signing up! you are logged in"
      redirect_to root_path
    else
      render :new
    end
  end 
  private 
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/friendships/create.html.erb
<%= link_to 'Back',friendships_path, class: "btn btn-basic" %>

app/views/friendships/index.html.erb
<div class="container">
  <h1>Friends</h1>
  <table class="table table-responsive">
    <thead>
      <th>User_Name</th>
      <th>Email</th> 
      <th>Action</th>
      <th colspan='3'></th>
    </thead>   
    <tbody>  
     <% @friendships.each do |friend_ship| %>

        <tr>
    
          <td><%= friend_ship.friend.username %></td>
          <td><%= friend_ship.friend.email %></td>
        
          <td><%= link_to "Remove", friendship_path(friend_ship), method: :delete,
          data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td> 
        </tr> 
     <% end %>
    </tbody>
 </table>
</div> 
<%= link_to 'Back', root_path, class: "btn btn-basic" %>








     

app/views/friendships/new.html.erb
<%= form_with model: @friendship do |form| %>
  <div>
    <%= form.label :username%><br>
    <%= form.text_field :username%>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
 <h3>Welcome to my app - <%= current_user.username %></h3>   
<% else %>
<%= link_to 'Sign_in',user_session_path %>
<%end%>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demotask1</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
    <%= render 'shared/navbar' %>
     <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
  
        <li class="nav-item">
          <a class="nav-link" href="/friendships">My Friends</a>
        </li>
         <li class="nav-item">
            <a class="nav-link" href="/users">Users</a>
         </li>
         
      </ul>
    </div>
  </div>
  <div class="d-grid gap-1 d-md-flex justify-content-md-end">
    <%= button_to "logout", destroy_user_session_path ,method: :delete %>
  </div> 
</nav>
      

app/views/users/index.html.erb
<div class="container">
  <h3>All Users</h3>
  <table class="table table-responsive">
    <thead>
      <th>User_Name</th>
      <th colspan='3'></th>  
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username  ,user_path(user)%></td> 
      
          <td><%= link_to "Add Friend",friendships_path(friendship: {:friend_id => user, :user_id =>current_user}), 
         :method => :post,  class: "btn btn-default" %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>
<%= link_to 'Back', root_path, class: "btn btn-basic" %>

    

app/views/users/show.html.erb
<h4>User Data</h4>
<div class = "user-page-content">
  <p>Id  :<%= @user.id %></p>
  <p>First_Name  :<%= @user.username %></p>
 
  <p>Email  :<%= @user.email %></p>
</div>

<!--
Hello my my email is <%= @user.email %>
<% if user_signed_in? %>
   <li>
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>

   <li><%= link_to 'All Users', users_path %>     
</li>
<% else %>
<li>
<%= link_to('Login', new_user_session_path)  %>  
</li>
<% end %>
<ul>

<% current_user.friend_requests.each do |request| %>
<h4>You have new friend requests from:</h4>
<li>
  <%= User.find(request.friend_id).email %>
  <%= link_to "Accept",  friend_request_path(friend_id: @friend),method:"put"   %>  
  <%= link_to "Decline", "#" %>
</li>
<% end %>
</ul>
-->